name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
         
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify -t sre-treats

      - name: Deploy
        run: |
          cd public
          pwd
          ls -lart
          git status
          git config -l
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin main
          
