name: Publish to sretreats

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: "Clone repository with submodules"
        uses: actions/checkout@master
        with:
          submodules: true

      - name: "Setup Hugo"
        run: brew install hugo
      
      - name: Build
        run: hugo --minify -t sre-treats

      - name: Deploy
        run: |
          cd public
          pwd
          ls -lart
          git status
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push origin main
          
