name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: "Clone repository with submodules"
        uses: actions/checkout@master
        with:
          submodules: true

      - uses: jsumners/gh-action-hugo-deploy@v1.0.0
        with:
          destination_repo: sretreats/sretreats.github.io
          destination_token: ${{ secrets.Deploy_Token }}
        
